version: '3'
services:
  server:
    build:
        context: .
        dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8080:3000"
    env_file:
      - .env
    volumes:
      - ./:/app
    command: ['npm', 'start']
  db:
    image: postgres:10
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
volumes:
  db-data: