version: '3'
services:
  server:
    container_name: type-server
    build:
        context: .
        dockerfile: Dockerfile
    depends_on:
      - db
    env_file: .env
    links:
      - "db:database"
    volumes:
      - .:/code
      - ./public:/opt/services/simplisaas/public
      - ./media:/opt/services/simplisaas/media
      
    command: ['npm', 'run', 'dev']

  nginx:
    container_name: type-nginx
    image: nginx:stable-alpine
    volumes:
        - .:/code
        - ./conf/nginx/:/etc/nginx/templates/
        - ./public:/opt/services/simplisaas/public
        - ./media:/opt/services/simplisaas/media
    environment:
      APP_PORT: ${APP_PORT}
      SERVER_NAME: ${SERVER_NAME}
    ports:
        - ${APP_PORT}:${APP_PORT}
    restart: always
    links:
      - server:type-server
    depends_on:
      - server
  
  db:
    image: mysql:8.0
    container_name: type-db
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'secret'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'secret'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - ${DB_PORT}:3306
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql

# Names our volume
volumes:
  my-db:
  media:
  public: